-- CREACION DE TABLAS

-- T_SIF_CONCEPTOS_HIST

CREATE TABLE "SIFCOS"."T_SIF_CONCEPTOS_HIST" 
   (	"ID_CONCEPTO_HISTORICO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CONCEPTO" NUMBER(10,0), 
	"ID_TIPO_CONCEPTO" NUMBER(10,0), 
	"IMPORTE" NUMBER(10,2), 
	"FEC_DESDE" DATE, 
	"FEC_HASTA" DATE, 
	 CONSTRAINT "PK_CONCEPTOS_HISTORICO" PRIMARY KEY ("ID_CONCEPTO_HISTORICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_CONCEPTOS_HISTORICO" ON "SIFCOS"."T_SIF_CONCEPTOS_HIST" ("ID_CONCEPTO_HISTORICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_CONCEPTOS_HIST" ADD CONSTRAINT "PK_CONCEPTOS_HISTORICO" PRIMARY KEY ("ID_CONCEPTO_HISTORICO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_CONCEPTOS_HIST" MODIFY ("ID_CONCEPTO_HISTORICO" NOT NULL ENABLE);
  
-- T_SIF_ENTIDADES

CREATE TABLE "SIFCOS"."T_SIF_ENTIDADES" 
   (	"ID_ENTIDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"CUIT" VARCHAR2(11), 
	"NRO_SIFCOS" NUMBER(10,0), 
	"LOCAL" VARCHAR2(5), 
	"OFICINA" VARCHAR2(5), 
	"STAND" VARCHAR2(5), 
	"LATITUD_UBI" VARCHAR2(50), 
	"LONGITUD_UBI" VARCHAR2(50), 
	"COBERTURA_MEDICA" VARCHAR2(1), 
	"SEGURO_LOCAL" VARCHAR2(1), 
	"ID_SEDE" VARCHAR2(3), 
	"PROPIETARIO" VARCHAR2(1), 
	"RESENIA" VARCHAR2(100), 
	"OBSERVACION" VARCHAR2(100), 
	"FEC_BAJA" DATE, 
	 CONSTRAINT "PK_ENTIDAD" PRIMARY KEY ("ID_ENTIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_ENT_PJSED" FOREIGN KEY ("CUIT", "ID_SEDE")
	  REFERENCES "T_COMUNES"."T_SEDES_PERSJURIDICA" ("CUIT", "ID_SEDE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE INDEX "SIFCOS"."IDX_ENT_PERSJUR" ON "SIFCOS"."T_SIF_ENTIDADES" ("CUIT", "ID_SEDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_LATITUD_UBI" ON "SIFCOS"."T_SIF_ENTIDADES" ("LATITUD_UBI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_SIF_ENT_NRO" ON "SIFCOS"."T_SIF_ENTIDADES" ("NRO_SIFCOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ENTIDAD" ON "SIFCOS"."T_SIF_ENTIDADES" ("ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ENTIDADES" ADD CONSTRAINT "PK_ENTIDAD" PRIMARY KEY ("ID_ENTIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ENTIDADES" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  
-- T_SIF_ESTADOS_TRAMITE

CREATE TABLE "SIFCOS"."T_SIF_ESTADOS_TRAMITE" 
   (	"ID_ESTADO_TRAMITE" NUMBER(3,0) NOT NULL ENABLE, 
	"N_ESTADO_TRAMITE" VARCHAR2(40), 
	 CONSTRAINT "PK_ESTADO_TRAMITE" PRIMARY KEY ("ID_ESTADO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ESTADO_TRAMITE" ON "SIFCOS"."T_SIF_ESTADOS_TRAMITE" ("ID_ESTADO_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ESTADOS_TRAMITE" ADD CONSTRAINT "PK_ESTADO_TRAMITE" PRIMARY KEY ("ID_ESTADO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ESTADOS_TRAMITE" MODIFY ("ID_ESTADO_TRAMITE" NOT NULL ENABLE);
  
-- T_SIF_GESTORES

CREATE TABLE "SIFCOS"."T_SIF_GESTORES" 
   (	"ID_GESTOR" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_TIPO_GESTOR" NUMBER(10,0), 
	"ID_SEXO" VARCHAR2(2), 
	"NRO_DOCUMENTO" VARCHAR2(12), 
	"PAI_COD_PAIS" VARCHAR2(5), 
	"ID_NUMERO" NUMBER(10,0), 
	 CONSTRAINT "PK_GESTORES_ENTIDAD" PRIMARY KEY ("ID_GESTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_SIF_PERS" FOREIGN KEY ("ID_SEXO", "NRO_DOCUMENTO", "PAI_COD_PAIS", "ID_NUMERO")
	  REFERENCES "RCIVIL"."T_IDENTIFICADORES_UNICOS" ("ID_SEXO", "NRO_DOCUMENTO", "PAI_COD_PAIS", "ID_NUMERO") ENABLE NOVALIDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_GESTORES_ENTIDAD" ON "SIFCOS"."T_SIF_GESTORES" ("ID_GESTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_GESTORES" ADD CONSTRAINT "PK_GESTORES_ENTIDAD" PRIMARY KEY ("ID_GESTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_GESTORES" MODIFY ("ID_GESTOR" NOT NULL ENABLE);  
  
-- T_SIF_HIST_CONCEPTOS

CREATE TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" 
   (	"ID_SIF_HIST_CONCEPTOS" VARCHAR2(25) NOT NULL ENABLE, 
	"N_CONCEPTO" VARCHAR2(150) NOT NULL ENABLE, 
	"MONTO" NUMBER(10,2) NOT NULL ENABLE, 
	"ID_TIPO_CONCEPTO" NUMBER(10,0), 
	"FEC_DESDE" DATE NOT NULL ENABLE, 
	"FEC_HASTA" DATE, 
	 CONSTRAINT "PK_TSIFHISTCONCEPTOS" PRIMARY KEY ("ID_SIF_HIST_CONCEPTOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_TSIFHISTCONCEPTOS" ON "SIFCOS"."T_SIF_HIST_CONCEPTOS" ("ID_SIF_HIST_CONCEPTOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" ADD CONSTRAINT "PK_TSIFHISTCONCEPTOS" PRIMARY KEY ("ID_SIF_HIST_CONCEPTOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" MODIFY ("ID_SIF_HIST_CONCEPTOS" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" MODIFY ("N_CONCEPTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" MODIFY ("MONTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_HIST_CONCEPTOS" MODIFY ("FEC_DESDE" NOT NULL ENABLE);  
  
  -- T_SIF_HIST_ESTADO
  
  CREATE TABLE "SIFCOS"."T_SIF_HIST_ESTADO" 
   (	"ID_TRAMITE_SIFCOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ESTADO_TRAMITE" NUMBER(3,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(500), 
	"FEC_DESDE_ESTADO" DATE NOT NULL ENABLE, 
	"FEC_HASTA_ESTADO" DATE, 
	"CUIL_USR_CIDI" VARCHAR2(11), 
	 CONSTRAINT "PK_HIST_ESTADO" PRIMARY KEY ("FEC_DESDE_ESTADO", "ID_TRAMITE_SIFCOS", "ID_ESTADO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_15" FOREIGN KEY ("ID_ESTADO_TRAMITE")
	  REFERENCES "SIFCOS"."T_SIF_ESTADOS_TRAMITE" ("ID_ESTADO_TRAMITE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE INDEX "SIFCOS"."IDX_SIFHISEST_ESTADO" ON "SIFCOS"."T_SIF_HIST_ESTADO" ("ID_ESTADO_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_HIST_ESTADO_ID" ON "SIFCOS"."T_SIF_HIST_ESTADO" ("ID_TRAMITE_SIFCOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_HIST_ESTADO" ON "SIFCOS"."T_SIF_HIST_ESTADO" ("FEC_DESDE_ESTADO", "ID_TRAMITE_SIFCOS", "ID_ESTADO_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_HIST_ESTADO" ADD CONSTRAINT "PK_HIST_ESTADO" PRIMARY KEY ("FEC_DESDE_ESTADO", "ID_TRAMITE_SIFCOS", "ID_ESTADO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_HIST_ESTADO" MODIFY ("ID_TRAMITE_SIFCOS" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_HIST_ESTADO" MODIFY ("ID_ESTADO_TRAMITE" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_HIST_ESTADO" MODIFY ("FEC_DESDE_ESTADO" NOT NULL ENABLE);
  
  -- T_SIF_LIQ_ORGANISMOS
  
  CREATE TABLE "SIFCOS"."T_SIF_LIQ_ORGANISMOS" 
   (	"ID_LIQ_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_LIQUIDACION" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTAL_LIQUIDADO" NUMBER(10,2), 
	"CANTIDAD" NUMBER(10,0), 
	 CONSTRAINT "PK_SIF_LIQ_ORGANISMOS" PRIMARY KEY ("ID_LIQ_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_LIQ_ORG_LIQ" FOREIGN KEY ("ID_LIQUIDACION")
	  REFERENCES "SIFCOS"."T_SIF_LIQUIDACIONES" ("ID_LIQUIDACION") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_LIQ_ORGANISMOS" ON "SIFCOS"."T_SIF_LIQ_ORGANISMOS" ("ID_LIQ_ORGANISMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_ORGANISMOS" ADD CONSTRAINT "PK_SIF_LIQ_ORGANISMOS" PRIMARY KEY ("ID_LIQ_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_ORGANISMOS" MODIFY ("ID_LIQ_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_ORGANISMOS" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_ORGANISMOS" MODIFY ("ID_LIQUIDACION" NOT NULL ENABLE);
  
  -- T_SIF_LIQ_TRAMITES
  
  CREATE TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" 
   (	"ID_LIQ_TRAMITE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_LIQ_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"NRO_TRAMITE_SIFCOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"MONTO_LIQUIDADO" NUMBER(10,2), 
	 CONSTRAINT "PK_SIF_LIQ_TRAMITES" PRIMARY KEY ("ID_LIQ_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_LIQ_TRAM_LIQ_ORG" FOREIGN KEY ("ID_LIQ_ORGANISMO")
	  REFERENCES "SIFCOS"."T_SIF_LIQ_ORGANISMOS" ("ID_LIQ_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_LIQ_TRAMITES" ON "SIFCOS"."T_SIF_LIQ_TRAMITES" ("ID_LIQ_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" ADD CONSTRAINT "PK_SIF_LIQ_TRAMITES" PRIMARY KEY ("ID_LIQ_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" MODIFY ("ID_LIQ_TRAMITE" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" MODIFY ("ID_LIQ_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" MODIFY ("NRO_TRAMITE_SIFCOS" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_LIQ_TRAMITES" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  
-- T_SIF_LIQUIDACIONES
  
  CREATE TABLE "SIFCOS"."T_SIF_LIQUIDACIONES" 
   (	"ID_LIQUIDACION" NUMBER(10,0) NOT NULL ENABLE, 
	"NRO_SIFCOS_DESDE" NUMBER(10,0), 
	"NRO_SIFCOS_HASTA" NUMBER(10,0), 
	"FEC_DESDE" DATE, 
	"FEC_HASTA" DATE, 
	"ID_TIPO_TRAMITE" NUMBER(10,0), 
	"ID_USUARIO" VARCHAR2(30), 
	"FEC_ALTA" DATE, 
	"NRO_EXPEDIENTE" VARCHAR2(50), 
	"NRO_RESOLUCION" VARCHAR2(50), 
	"FECHA_RESOLUCION" DATE, 
	 CONSTRAINT "PK_SIF_LIQUIDACIONES" PRIMARY KEY ("ID_LIQUIDACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_LIQUIDACIONES" ON "SIFCOS"."T_SIF_LIQUIDACIONES" ("ID_LIQUIDACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_LIQUIDACIONES" ADD CONSTRAINT "PK_SIF_LIQUIDACIONES" PRIMARY KEY ("ID_LIQUIDACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_LIQUIDACIONES" MODIFY ("ID_LIQUIDACION" NOT NULL ENABLE);
  
  -- T_SIF_ORGANISMOS
  
  CREATE TABLE "SIFCOS"."T_SIF_ORGANISMOS" 
   (	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"CUIT" VARCHAR2(11), 
	"ID_SEDE" VARCHAR2(3), 
	"DESCRIPCION" VARCHAR2(100), 
	"ID_ORGANISMO_SUPERIOR" NUMBER(10,0), 
	"SN_LIQUIDABLE" VARCHAR2(1), 
	 CONSTRAINT "PK_ORGANISMOS" PRIMARY KEY ("ID_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_ORG_PERJUR" FOREIGN KEY ("CUIT", "ID_SEDE")
	  REFERENCES "T_COMUNES"."T_SEDES_PERSJURIDICA" ("CUIT", "ID_SEDE") ENABLE, 
	 CONSTRAINT "FK_ORG_ORG" FOREIGN KEY ("ID_ORGANISMO_SUPERIOR")
	  REFERENCES "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ORGANISMOS" ON "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS" ADD CONSTRAINT "PK_ORGANISMOS" PRIMARY KEY ("ID_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  
  -- T_SIF_ORGANISMOS_COBERTURA
  
  CREATE TABLE "SIFCOS"."T_SIF_ORGANISMOS_COBERTURA" 
   (	"ID_ORGANISMO" NUMBER(15,5) NOT NULL ENABLE, 
	"ID_ORGANISMO_CUBIERTO" NUMBER(15,5) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ORG_COB" PRIMARY KEY ("ID_ORGANISMO", "ID_ORGANISMO_CUBIERTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_ORG_COB_1" FOREIGN KEY ("ID_ORGANISMO_CUBIERTO")
	  REFERENCES "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") ENABLE, 
	 CONSTRAINT "FK_ORG_COB_2" FOREIGN KEY ("ID_ORGANISMO")
	  REFERENCES "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ORG_COB" ON "SIFCOS"."T_SIF_ORGANISMOS_COBERTURA" ("ID_ORGANISMO", "ID_ORGANISMO_CUBIERTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_COBERTURA" ADD CONSTRAINT "PK_ORG_COB" PRIMARY KEY ("ID_ORGANISMO", "ID_ORGANISMO_CUBIERTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_COBERTURA" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_COBERTURA" MODIFY ("ID_ORGANISMO_CUBIERTO" NOT NULL ENABLE);
  
  -- T_SIF_ORGANISMOS_POR_LOCALDIAD
  
  CREATE TABLE "SIFCOS"."T_SIF_ORGANISMOS_POR_LOCALDIAD" 
   (	"ID_LOCALIDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100), 
	"FEC_ALTA" DATE, 
	"USR_ALTA" VARCHAR2(20), 
	"DESTINO" VARCHAR2(100), 
	 CONSTRAINT "PK_ORGANISMOS_POR_LOCALIDAD" PRIMARY KEY ("ID_LOCALIDAD", "ID_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE, 
	 CONSTRAINT "FK_ORG_DOM_MAN" FOREIGN KEY ("ID_LOCALIDAD")
	  REFERENCES "DOM_MANAGER"."DOM_LOCALIDADES" ("ID_LOCALIDAD") ENABLE, 
	 CONSTRAINT "FK_ORG_LOC_ORG" FOREIGN KEY ("ID_ORGANISMO")
	  REFERENCES "SIFCOS"."T_ORGANISMOS" ("ID_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ORGANISMOS_POR_LOCALIDAD" ON "SIFCOS"."T_SIF_ORGANISMOS_POR_LOCALDIAD" ("ID_LOCALIDAD", "ID_ORGANISMO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA" ;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_POR_LOCALDIAD" ADD CONSTRAINT "PK_ORGANISMOS_POR_LOCALIDAD" PRIMARY KEY ("ID_LOCALIDAD", "ID_ORGANISMO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_POR_LOCALDIAD" MODIFY ("ID_LOCALIDAD" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_ORGANISMOS_POR_LOCALDIAD" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  
-- T_SIF_ORIGENES_PROVEEDOR
  
  CREATE TABLE "SIFCOS"."T_SIF_ORIGENES_PROVEEDOR" 
   (	"ID_ORIGEN_PROVEEDOR" NUMBER(10,0) NOT NULL ENABLE, 
	"N_ORIGEN_PROVEEDOR" VARCHAR2(100), 
	 CONSTRAINT "PK_ORIGENES" PRIMARY KEY ("ID_ORIGEN_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ORIGENES" ON "SIFCOS"."T_SIF_ORIGENES_PROVEEDOR" ("ID_ORIGEN_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ORIGENES_PROVEEDOR" ADD CONSTRAINT "PK_ORIGENES" PRIMARY KEY ("ID_ORIGEN_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ORIGENES_PROVEEDOR" MODIFY ("ID_ORIGEN_PROVEEDOR" NOT NULL ENABLE);
  
  -- T_SIF_PARAMETROS_GRAL
  
  CREATE TABLE "SIFCOS"."T_SIF_PARAMETROS_GRAL" 
   (	"ID_PARAMETRO_GRAL" NUMBER(9,0), 
	"VALOR" VARCHAR2(50), 
	"DESCRIPCION" VARCHAR2(500), 
	 CONSTRAINT "PK_T_PARAM_GRAL" PRIMARY KEY ("ID_PARAMETRO_GRAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_T_PARAM_GRAL" ON "SIFCOS"."T_SIF_PARAMETROS_GRAL" ("ID_PARAMETRO_GRAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_PARAMETROS_GRAL" ADD CONSTRAINT "PK_T_PARAM_GRAL" PRIMARY KEY ("ID_PARAMETRO_GRAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  
  -- T_SIF_PRODUCTOS
  
  CREATE TABLE "SIFCOS"."T_SIF_PRODUCTOS" 
   (	"ID_PRODUCTO" VARCHAR2(5) NOT NULL ENABLE, 
	"N_PRODUCTO" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_SIF_PRODUCTOS" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_PRODUCTOS" ON "SIFCOS"."T_SIF_PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_PRODUCTOS" ADD CONSTRAINT "PK_SIF_PRODUCTOS" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_PRODUCTOS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_PRODUCTOS" MODIFY ("N_PRODUCTO" NOT NULL ENABLE);
  
  --  T_SIF_PRODUCTOS_ACTIVIDAD
  
  CREATE TABLE "SIFCOS"."T_SIF_PRODUCTOS_ACTIVIDAD" 
   (	"ID_PRODUCTO" VARCHAR2(5), 
	"ID_ACTIVIDAD_CLANAE" VARCHAR2(10), 
	"FECHA_INICIO_ACT" DATE, 
	 CONSTRAINT "PK_SIF_PRODUCTOS_ACTIVIDAD" PRIMARY KEY ("ID_PRODUCTO", "ID_ACTIVIDAD_CLANAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_PRODUCTOS_ACTIVIDAD" ON "SIFCOS"."T_SIF_PRODUCTOS_ACTIVIDAD" ("ID_PRODUCTO", "ID_ACTIVIDAD_CLANAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_PRODUCTOS_ACTIVIDAD" ADD CONSTRAINT "PK_SIF_PRODUCTOS_ACTIVIDAD" PRIMARY KEY ("ID_PRODUCTO", "ID_ACTIVIDAD_CLANAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  
  -- T_SIF_PRODUCTOS_TRAMITE
  
  CREATE TABLE "SIFCOS"."T_SIF_PRODUCTOS_TRAMITE" 
   (	"ID_TRAMITE_SIFCOS" NUMBER(10,0), 
	"ID_PRODUCTO" VARCHAR2(5), 
	"CONFIRMADO" VARCHAR2(1), 
	 CONSTRAINT "PK_PRODUCTOS_TRAMITE" PRIMARY KEY ("ID_TRAMITE_SIFCOS", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_PRODUCTOS_TRAMITE" ON "SIFCOS"."T_SIF_PRODUCTOS_TRAMITE" ("ID_TRAMITE_SIFCOS", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_PRODUCTOS_TRAMITE" ADD CONSTRAINT "PK_PRODUCTOS_TRAMITE" PRIMARY KEY ("ID_TRAMITE_SIFCOS", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  
  -- T_SIF_RELEVAMIENTOS
  
  CREATE TABLE "SIFCOS"."T_SIF_RELEVAMIENTOS" 
   (	"ID_RELEVAMIENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"N_RELEVAMIENTO" VARCHAR2(200) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(25) NOT NULL ENABLE, 
	"OBSERVACIONES" VARCHAR2(1000), 
	"USR_ALTA" VARCHAR2(30), 
	"FEC_ALTA" DATE, 
	"USR_MODIF" VARCHAR2(30), 
	"FEC_MODIF" DATE, 
	 CONSTRAINT "PK_RELEVA" PRIMARY KEY ("ID_RELEVAMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_RELEVA" ON "SIFCOS"."T_SIF_RELEVAMIENTOS" ("ID_RELEVAMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA" ;
  ALTER TABLE "SIFCOS"."T_SIF_RELEVAMIENTOS" ADD CONSTRAINT "PK_RELEVA" PRIMARY KEY ("ID_RELEVAMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_RELEVAMIENTOS" MODIFY ("ID_RELEVAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEVAMIENTOS" MODIFY ("N_RELEVAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEVAMIENTOS" MODIFY ("CODIGO" NOT NULL ENABLE);
  
  -- T_SIF_RELEV_DETALLE
  
  CREATE TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" 
   (	"ID_RELEV_DETALLE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_ENTIDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_RELEVAMIENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"PRECIO" NUMBER(15,2) NOT NULL ENABLE, 
	"FEC_RELEVAMIENTO" DATE NOT NULL ENABLE, 
	"OBSERVACIONES" VARCHAR2(1000), 
	"VIGENTE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"USR_ALTA" VARCHAR2(30), 
	"FEC_ALTA" DATE, 
	"USR_MODIF" VARCHAR2(30), 
	"FEC_MODIF" DATE, 
	 CONSTRAINT "PKRELEVDETALLE" PRIMARY KEY ("ID_RELEV_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE, 
	 CONSTRAINT "FKRELEV" FOREIGN KEY ("ID_RELEVAMIENTO")
	  REFERENCES "SIFCOS"."T_SIF_RELEVAMIENTOS" ("ID_RELEVAMIENTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PKRELEVDETALLE" ON "SIFCOS"."T_SIF_RELEV_DETALLE" ("ID_RELEV_DETALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA" ;
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" ADD CONSTRAINT "PKRELEVDETALLE" PRIMARY KEY ("ID_RELEV_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("ID_RELEV_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("ID_RELEVAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("FEC_RELEVAMIENTO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RELEV_DETALLE" MODIFY ("VIGENTE" NOT NULL ENABLE);
  
  --   T_SIF_REP_LEGAL
  
  CREATE TABLE "SIFCOS"."T_SIF_REP_LEGAL" 
   (	"ID_REP_LEGAL" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_CARGO" NUMBER(10,0), 
	"ID_SEXO" VARCHAR2(2), 
	"NRO_DOCUMENTO" VARCHAR2(12), 
	"PAI_COD_PAIS" VARCHAR2(5), 
	"ID_NUMERO" NUMBER(10,0), 
	 CONSTRAINT "PK_CARGOS_ENTIDAD" PRIMARY KEY ("ID_REP_LEGAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_CARGOS_ENTIDAD" ON "SIFCOS"."T_SIF_REP_LEGAL" ("ID_REP_LEGAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_REP_LEGAL" ADD CONSTRAINT "PK_CARGOS_ENTIDAD" PRIMARY KEY ("ID_REP_LEGAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_REP_LEGAL" MODIFY ("ID_REP_LEGAL" NOT NULL ENABLE);
  
  -- T_SIF_ROLES
  
  CREATE TABLE "SIFCOS"."T_SIF_ROLES" 
   (	"ID_ROL" NUMBER(10,0) NOT NULL ENABLE, 
	"N_ROL" VARCHAR2(100), 
	"ID_APLICACION" NUMBER(4,0), 
	 CONSTRAINT "PK_ROLL" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_ROL_APP" FOREIGN KEY ("ID_APLICACION")
	  REFERENCES "T_COMUNES"."T_APLICACIONES" ("ID_APP") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_ROLL" ON "SIFCOS"."T_SIF_ROLES" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_ROLES" ADD CONSTRAINT "PK_ROLL" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_ROLES" MODIFY ("ID_ROL" NOT NULL ENABLE);
  
  -- T_SIF_RUBROS
  
  CREATE TABLE "SIFCOS"."T_SIF_RUBROS" 
   (	"ID_RUBRO" NUMBER(15,0) NOT NULL ENABLE, 
	"N_RUBRO" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_CATEGORIA" NUMBER(8,0), 
	 CONSTRAINT "PK_SIF_RUBROS" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_RUBROS" ON "SIFCOS"."T_SIF_RUBROS" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS" ADD CONSTRAINT "PK_SIF_RUBROS" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS" MODIFY ("N_RUBRO" NOT NULL ENABLE);
  
  --  T_SIF_RUBROS_ACTIVIDAD
  
  CREATE TABLE "SIFCOS"."T_SIF_RUBROS_ACTIVIDAD" 
   (	"ID_RUBRO" NUMBER(15,0) NOT NULL ENABLE, 
	"ID_ACTIVIDAD_CLANAE" VARCHAR2(10) NOT NULL ENABLE, 
	"FECHA_INICIO_ACT" DATE, 
	 CONSTRAINT "PK_SIF_RUBROS_ACTIVIDAD" PRIMARY KEY ("ID_RUBRO", "ID_ACTIVIDAD_CLANAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_RUBROS_ACTIVIDAD" ON "SIFCOS"."T_SIF_RUBROS_ACTIVIDAD" ("ID_RUBRO", "ID_ACTIVIDAD_CLANAE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS_ACTIVIDAD" ADD CONSTRAINT "PK_SIF_RUBROS_ACTIVIDAD" PRIMARY KEY ("ID_RUBRO", "ID_ACTIVIDAD_CLANAE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS_ACTIVIDAD" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_RUBROS_ACTIVIDAD" MODIFY ("ID_ACTIVIDAD_CLANAE" NOT NULL ENABLE);
  
  -- T_SIF_SUPERFICIES_EMPRESA
  
  CREATE TABLE "SIFCOS"."T_SIF_SUPERFICIES_EMPRESA" 
   (	"ID_TRAMITE_SIFCOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_TIPO_SUPERFICIE" NUMBER(2,0) NOT NULL ENABLE, 
	"SUPERFICIE" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  ALTER TABLE "SIFCOS"."T_SIF_SUPERFICIES_EMPRESA" MODIFY ("ID_TRAMITE_SIFCOS" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_SUPERFICIES_EMPRESA" MODIFY ("ID_TIPO_SUPERFICIE" NOT NULL ENABLE);

  
-- T_SIF_TASAS

CREATE TABLE "SIFCOS"."T_SIF_TASAS" 
   (	"NRO_TRANSACCION" VARCHAR2(20), 
	"NRO_TRAMITE_SIFCOS" NUMBER(10,0), 
	"PAGADA" VARCHAR2(1), 
	"FECHA_ALTA" DATE, 
	"NROLIQUIDACIONORIGINAL" VARCHAR2(16), 
	 CONSTRAINT "PK_T_SIF_TASAS" PRIMARY KEY ("NRO_TRANSACCION", "NRO_TRAMITE_SIFCOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_PAG" ON "SIFCOS"."T_SIF_TASAS" ("PAGADA", "NRO_TRANSACCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_T_SIF_TASAS" ON "SIFCOS"."T_SIF_TASAS" ("NRO_TRANSACCION", "NRO_TRAMITE_SIFCOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TASAS" ADD CONSTRAINT "PK_T_SIF_TASAS" PRIMARY KEY ("NRO_TRANSACCION", "NRO_TRAMITE_SIFCOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  
  -- T_SIF_TIPOS_CARGO
  
  CREATE TABLE "SIFCOS"."T_SIF_TIPOS_CARGO" 
   (	"ID_CARGO" NUMBER(10,0) NOT NULL ENABLE, 
	"N_CARGO" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TIPO_CARGOS" PRIMARY KEY ("ID_CARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_TIPO_CARGOS" ON "SIFCOS"."T_SIF_TIPOS_CARGO" ("ID_CARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_CARGO" ADD CONSTRAINT "PK_TIPO_CARGOS" PRIMARY KEY ("ID_CARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_CARGO" MODIFY ("ID_CARGO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_CARGO" MODIFY ("N_CARGO" NOT NULL ENABLE);
  
  -- T_SIF_TIPOS_CONCEPTO
  
  CREATE TABLE "SIFCOS"."T_SIF_TIPOS_CONCEPTO" 
   (	"ID_TIPO_CONCEPTO" NUMBER(10,0) NOT NULL ENABLE, 
	"N_TIPO_CONCEPTO" VARCHAR2(50), 
	 CONSTRAINT "PK_TIPOS_CONCEPTO" PRIMARY KEY ("ID_TIPO_CONCEPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_TIPOS_CONCEPTO" ON "SIFCOS"."T_SIF_TIPOS_CONCEPTO" ("ID_TIPO_CONCEPTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_CONCEPTO" ADD CONSTRAINT "PK_TIPOS_CONCEPTO" PRIMARY KEY ("ID_TIPO_CONCEPTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_CONCEPTO" MODIFY ("ID_TIPO_CONCEPTO" NOT NULL ENABLE);
  GRANT SELECT ON "SIFCOS"."T_SIF_TIPOS_CONCEPTO" TO "USR_SIFCOS";
  
  -- T_SIF_TIPOS_GESTOR
  
  CREATE TABLE "SIFCOS"."T_SIF_TIPOS_GESTOR" 
   (	"ID_TIPO_GESTOR" NUMBER(10,0) NOT NULL ENABLE, 
	"N_TIPO_GESTOR" VARCHAR2(100), 
	 CONSTRAINT "PK_GESTORES" PRIMARY KEY ("ID_TIPO_GESTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_GESTORES" ON "SIFCOS"."T_SIF_TIPOS_GESTOR" ("ID_TIPO_GESTOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_GESTOR" ADD CONSTRAINT "PK_GESTORES" PRIMARY KEY ("ID_TIPO_GESTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_GESTOR" MODIFY ("ID_TIPO_GESTOR" NOT NULL ENABLE);
  
  -- T_SIF_TIPOS_SUPERFICIE
  
  CREATE TABLE "SIFCOS"."T_SIF_TIPOS_SUPERFICIE" 
   (	"ID_TIPO_SUPERFICIE" NUMBER(2,0) NOT NULL ENABLE, 
	"N_TIPO_SUPERFICIE" VARCHAR2(100) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_SUPERFICIE" MODIFY ("ID_TIPO_SUPERFICIE" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_SUPERFICIE" MODIFY ("N_TIPO_SUPERFICIE" NOT NULL ENABLE);
  
  -- T_SIF_TIPOS_TRAMITE
  
  CREATE TABLE "SIFCOS"."T_SIF_TIPOS_TRAMITE" 
   (	"ID_TIPO_TRAMITE" NUMBER(10,0) NOT NULL ENABLE, 
	"N_TIPO_TRAMITE" VARCHAR2(50), 
	 CONSTRAINT "PK_TIPO_TRAMITES" PRIMARY KEY ("ID_TIPO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_TIPO_TRAMITES" ON "SIFCOS"."T_SIF_TIPOS_TRAMITE" ("ID_TIPO_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_TRAMITE" ADD CONSTRAINT "PK_TIPO_TRAMITES" PRIMARY KEY ("ID_TIPO_TRAMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_TIPOS_TRAMITE" MODIFY ("ID_TIPO_TRAMITE" NOT NULL ENABLE);
  
  -- T_SIF_TRAMITES_SIFCOS
  
  CREATE TABLE "SIFCOS"."T_SIF_TRAMITES_SIFCOS" 
   (	"NRO_TRAMITE_SIFCOS" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_LOCALIDAD_CERTIFICA_RESP" VARCHAR2(100), 
	"FEC_CERTIFICACIÓN_RESP" DATE, 
	"CAPACITACION_ULT_ANIO" VARCHAR2(1), 
	"ID_ENTIDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"CUIL_USUARIO_CIDI" VARCHAR2(11) NOT NULL ENABLE, 
	"ID_TIPO_TRAMITE" NUMBER(10,0) NOT NULL ENABLE, 
	"ID_VIN_DOM_LEGAL" NUMBER(20,0), 
	"FEC_INI_TRAMITE" DATE, 
	"ID_CARGO_ENTIDAD" NUMBER(10,0), 
	"ID_GESTOR_ENTIDAD" NUMBER(10,0), 
	"ID_ORIGEN_PROVEEDOR" NUMBER(10,0), 
	"ID_VIN_DOM_LOCAL" NUMBER(20,0), 
	"CANT_PERS_TOTAL" NUMBER(5,0), 
	"CANT_PERS_REL_DEPENDENCIA" NUMBER(5,0), 
	"ID_ACTIVIDAD_PPAL" VARCHAR2(10), 
	"FEC_INI_ACT_PPAL" DATE, 
	"ID_ACTIVIDAD_SRIA" VARCHAR2(10), 
	"FEC_INI_ACT_SRIA" DATE, 
	"FEC_ALTA" DATE, 
	"RANGO_ALQ" VARCHAR2(20), 
	"FEC_VENCIMIENTO" DATE, 
	"CANT_REEMP" NUMBER(5,0), 
	"ID_ORGANISMO_ALTA" NUMBER(10,0), 
	"ID_RUBRO_PRI" NUMBER(15,0), 
	"ID_RUBRO_SEC" NUMBER(15,0), 
	"ID_DOCUMENTO1_CDD" NUMBER DEFAULT null, 
	"ID_DOCUMENTO2_CDD" NUMBER DEFAULT null, 
	"ID_DOCUMENTO3_CDD" NUMBER, 
	"ID_DOCUMENTO4_CDD" NUMBER, 
	 CONSTRAINT "FK_51" FOREIGN KEY ("ID_ACTIVIDAD_SRIA", "FEC_INI_ACT_SRIA")
	  REFERENCES "T_COMUNES"."T_ACTIVIDADES" ("ID_ACTIVIDAD", "FECHA_INICIO_ACT") ENABLE, 
	 CONSTRAINT "FK_TRAM_RUBROPRI" FOREIGN KEY ("ID_RUBRO_PRI")
	  REFERENCES "SIFCOS"."T_SIF_RUBROS" ("ID_RUBRO") ENABLE, 
	 CONSTRAINT "FK_22" FOREIGN KEY ("ID_ORIGEN_PROVEEDOR")
	  REFERENCES "SIFCOS"."T_SIF_ORIGENES_PROVEEDOR" ("ID_ORIGEN_PROVEEDOR") ENABLE, 
	 CONSTRAINT "FK_50" FOREIGN KEY ("ID_ACTIVIDAD_PPAL", "FEC_INI_ACT_PPAL")
	  REFERENCES "T_COMUNES"."T_ACTIVIDADES" ("ID_ACTIVIDAD", "FECHA_INICIO_ACT") ENABLE, 
	 CONSTRAINT "FK_5" FOREIGN KEY ("ID_ENTIDAD")
	  REFERENCES "SIFCOS"."T_SIF_ENTIDADES" ("ID_ENTIDAD") ENABLE, 
	 CONSTRAINT "FK_8" FOREIGN KEY ("ID_TIPO_TRAMITE")
	  REFERENCES "SIFCOS"."T_SIF_TIPOS_TRAMITE" ("ID_TIPO_TRAMITE") ENABLE, 
	 CONSTRAINT "FK_TRAM_RUBROSEC" FOREIGN KEY ("ID_RUBRO_SEC")
	  REFERENCES "SIFCOS"."T_SIF_RUBROS" ("ID_RUBRO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE INDEX "SIFCOS"."IDX_ID_RUBRO" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("ID_RUBRO_PRI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_SIFTRAMSIF_ENTIDAD" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("ID_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_SIFTRAMSIF_FECALTA" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("FEC_ALTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE UNIQUE INDEX "SIFCOS"."IDX_SIF_TRAMITES_SIFCOS" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("NRO_TRAMITE_SIFCOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_TIPO_TRAM" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("NRO_TRAMITE_SIFCOS", "ID_ENTIDAD", "ID_TIPO_TRAMITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_TRAMI_SIFCOS" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("NRO_TRAMITE_SIFCOS", "ID_CARGO_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_TRAMI_SIFCOS_GESTOR" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("NRO_TRAMITE_SIFCOS", "ID_GESTOR_ENTIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."IDX_T_SIF_TRAM_ENT_FEC" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("ID_ENTIDAD", "FEC_VENCIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."ID_SIFTRASIF_IDVIN" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("ID_VIN_DOM_LEGAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  CREATE INDEX "SIFCOS"."ID_SIFTRASIF_IDVINLOCAL" ON "SIFCOS"."T_SIF_TRAMITES_SIFCOS" ("ID_VIN_DOM_LOCAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_TRAMITES_SIFCOS" MODIFY ("NRO_TRAMITE_SIFCOS" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_TRAMITES_SIFCOS" MODIFY ("ID_ENTIDAD" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_TRAMITES_SIFCOS" MODIFY ("CUIL_USUARIO_CIDI" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_TRAMITES_SIFCOS" MODIFY ("ID_TIPO_TRAMITE" NOT NULL ENABLE);
  
  -- T_SIF_USUARIOS_CIDI
  
  CREATE TABLE "SIFCOS"."T_SIF_USUARIOS_CIDI" 
   (	"ID_USUARIO_CIDI" VARCHAR2(11) NOT NULL ENABLE, 
	"FEC_ULT_ACCESO" DATE, 
	"ID_ROL" NUMBER(10,0) NOT NULL ENABLE, 
	"N_APLICACION" VARCHAR2(50), 
	"PERMISO" VARCHAR2(20), 
	 CONSTRAINT "FK_10" FOREIGN KEY ("ID_ROL")
	  REFERENCES "SIFCOS"."T_SIF_ROLES" ("ID_ROL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_SIF_USUARIOS_CIDI" ON "SIFCOS"."T_SIF_USUARIOS_CIDI" ("ID_USUARIO_CIDI", "ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_CIDI" MODIFY ("ID_USUARIO_CIDI" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_CIDI" MODIFY ("ID_ROL" NOT NULL ENABLE);
  CREATE TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" 
   (	"CUIL_USR_CIDI" VARCHAR2(11) NOT NULL ENABLE, 
	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"FEC_DESDE" DATE NOT NULL ENABLE, 
	"FEC_HASTA" DATE, 
	 CONSTRAINT "PK_USUARIOS_ORGANISMO" PRIMARY KEY ("CUIL_USR_CIDI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_USUORG_ORG" FOREIGN KEY ("ID_ORGANISMO")
	  REFERENCES "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_USUARIOS_ORGANISMO" ON "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" ("CUIL_USR_CIDI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" ADD CONSTRAINT "PK_USUARIOS_ORGANISMO" PRIMARY KEY ("CUIL_USR_CIDI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("CUIL_USR_CIDI" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("FEC_DESDE" NOT NULL ENABLE);
  
  -- T_SIF_USUARIOS_ORGANISMO
  
  CREATE TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" 
   (	"CUIL_USR_CIDI" VARCHAR2(11) NOT NULL ENABLE, 
	"ID_ORGANISMO" NUMBER(10,0) NOT NULL ENABLE, 
	"FEC_DESDE" DATE NOT NULL ENABLE, 
	"FEC_HASTA" DATE, 
	 CONSTRAINT "PK_USUARIOS_ORGANISMO" PRIMARY KEY ("CUIL_USR_CIDI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE, 
	 CONSTRAINT "FK_USUORG_ORG" FOREIGN KEY ("ID_ORGANISMO")
	  REFERENCES "SIFCOS"."T_SIF_ORGANISMOS" ("ID_ORGANISMO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_DATA"   NO INMEMORY ;
  CREATE UNIQUE INDEX "SIFCOS"."PK_USUARIOS_ORGANISMO" ON "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" ("CUIL_USR_CIDI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX" ;
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" ADD CONSTRAINT "PK_USUARIOS_ORGANISMO" PRIMARY KEY ("CUIL_USR_CIDI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CBA1_IDX"  ENABLE;
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("CUIL_USR_CIDI" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("ID_ORGANISMO" NOT NULL ENABLE);
  ALTER TABLE "SIFCOS"."T_SIF_USUARIOS_ORGANISMO" MODIFY ("FEC_DESDE" NOT NULL ENABLE);
  
  
  -- CREACION DE SECUENCIAS
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_ENTIDADES"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 61201 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_ENTIDADES" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_GESTORES"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 90779 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_GESTORES" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_LIQ_ORGANISMOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 708 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_LIQ_ORGANISMOS" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_LIQ_TRAMITES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 191795 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_LIQ_TRAMITES" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_LIQUIDACIONES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_LIQUIDACIONES" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_NROSIFCOS"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 START WITH 96116 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_NROSIFCOS" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_PRODUCTOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_REP_LEGAL"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 91761 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_REP_LEGAL" TO "USR_SIFCOS";
  
  CREATE SEQUENCE  "SIFCOS"."SEQ_SIF_TRAMITES"  MINVALUE 1 MAXVALUE 999999999999999 INCREMENT BY 1 START WITH 250013 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  GRANT SELECT ON "SIFCOS"."SEQ_SIF_TRAMITES" TO "USR_SIFCOS";